version: '3'

services:
    web:
        image: nginx:alpine
        volumes:
            - ./:/var/www/html
            - ./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template
        environment:
            - HOST=${HOST}
        command: >
            /bin/sh -c "cp /etc/nginx/conf.d/default.template /etc/nginx/conf.d/default.conf
            && export hosts=\"$$(echo $$HOST | sed 's/,/ /g')\"
            && envsubst '$$hosts' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf
            && nginx -g 'daemon off;'"
        depends_on:
            - php
            - mysqldb
    php:
        image: fulldigits/php:7.2-wordpress
        volumes:
            - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./:/var/www/html
            - ./data/uploads:/var/www/html/wp-content/uploads
    
    mysqldb:
        image: mysql:5
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_RANDOM_ROOT_PASSWORD='yes'
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./data/db/mysql:/var/lib/mysql
    
volumes:
    tdc-node-modules:
    tdc-caches:
